# Generated by Django 4.1.3 on 2023-03-05 02:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='short_day',
        ),
        migrations.RemoveField(
            model_name='income',
            name='short_day',
        ),
        migrations.AddField(
            model_name='expense',
            name='day_of_week',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='day_of_week',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
            preserve_default=False,
        ),
    ]
