# Generated by Django 4.1.3 on 2023-03-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_expense_short_day_remove_income_short_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='income',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
