# Generated by Django 4.1.3 on 2023-03-18 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_expense_is_delete_remove_income_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='income',
            name='date_time',
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
