# Generated by Django 4.1.3 on 2023-03-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_expense_date_time_remove_income_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor',
            name='phone_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='phone_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
