# Generated by Django 4.1.3 on 2023-05-07 15:30

from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.models import User
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0007_remove_creditor_is_settled_remove_creditor_phone_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditor",
            name="user",
            field=models.ForeignKey(
                to="auth.user", on_delete=models.CASCADE, default=3
            ),
        ),
        migrations.AddField(
            model_name="debtor",
            name="user",
            field=models.ForeignKey(
                to="auth.user", on_delete=models.CASCADE, default=3
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="user",
            field=models.ForeignKey(
                to="auth.user", on_delete=models.CASCADE, default=3
            ),
        ),
        migrations.AddField(
            model_name="income",
            name="user",
            field=models.ForeignKey(
                to="auth.user", on_delete=models.CASCADE, default=3
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
